trigger:
  branches:
    include:
      - master
      - develop
      - feature/*
      - hotfix/*
      - bugfix/*
      - release/*

resources:
  repositories:
  - repository: templates
    type: github
    name: xen22-solarmonitor/Common.Infrastructure.CI
    endpoint: 'xen22-solarmonitor'

variables:
  # enable debug logging in the pipeline
  System.Debug: true
  customDotnetVersion: '3.0.100-preview7-012821'

  # Azure DevOps variables are transformed into environment variables, with these variables we
  # avoid the first time experience and telemetry to speed up the build.
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  
stages:
  - template: 'azure-pipelines/pipeline.api.yml@templates'
    parameters:
      sdk: '$(customDotnetVersion)'
      buildConfiguration: 'Release'
      apiName: 'Api.Core.SolarMeasurements'
      apiDescription: "Solar measurements Core API"
      productDescription: "SolarMonitor"
      dockerContainerTag: 'api.core.solarmeasurements'
      customDotnetVersion: '3.0.100-preview7-012821'
      dockerId: 'solarmonitor'

